name: Deployment
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            set -e
            cd ${{ secrets.APP_PATH }}
            git checkout master
            git pull

            kind delete clusters --all

            kind create cluster --config ./kind/config.yaml -n projet
            
            kubectl create namespace projet
            
            docker build -t 2024_kubernetes_post_consumer -f ./post_consumer/Dockerfile .
            kind load docker-image 2024_kubernetes_post_consumer -n projet
            
            docker build -t 2024_kubernetes_post_pusher -f ./post_pusher/Dockerfile .
            kind load docker-image 2024_kubernetes_post_pusher -n projet
            
            kubectl apply -f cours_kafka/post_consumer/deployment.yaml -n projet
            
            kubectl apply -f cours_kafka/ui/deployment.yaml -n projet
            kubectl apply -f cours_kafka/ui/service.yaml -n projet
            
            kubectl apply -f cours_kafka/kafka/deployment.yaml -n projet
            kubectl apply -f cours_kafka/kafka/service.yaml -n projet
            
            kubectl apply -f airflow/airflow-dags-pv.yaml -n projet
            kubectl apply -f airflow/airflow-dags-pvc.yaml -n projet
            
            helm install airflow airflow-stable/airflow --version 8.9.0 --values ./airflow/custom-values.yaml --namespace projet
          EOF
      - name: Verify Deployments
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            kubectl get pods -n projet
            kubectl get services -n projet
          EOF